<a href="https://colab.research.google.com/github/sungminparklee/week4hw/blob/main/Copy_of_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Student Name

Sungmin Park

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://lsis5425-fall2023.github.io/group-3/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Fry Bread",
  "creator": "Kevin Maillard; illst. Juana Martinez-Neal",
  "date": "2019",
  "description": "This portrayal of a modern Native American family, told in lively and powerful verse, uses fry bread as a metaphor for love, sharing, and honoring the old while embracing the new.",
  "subject": "Friendship and moving",
  "source": "978-1-62672-746-5",
  "identifier": "E, MAI",
  "type": "Picture book",
  "format": "image/jpeg",
  "reference_url": "https://lsis5425-fall2023.github.io/group-3/item.html?id=coll007"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://lsis5425-fall2023.github.io/group-3/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "building a sense of community": 1,
        "class community": 1,
        "culture practices": 1,
        "divorce": 1,
        "family and tradition": 1,
        "father daughter relationship, hairstyles": 1,
        "friendship and moving": 1,
        "housing insecurity": 1,
        "immigration, hispanic representation": 1,
        "indigenous representation": 2,
        "individuality": 1,
        "individuality, friendship, and schools": 1,
        "multicultural representation (chinese and jewish)": 1,
        "multicultural representation (eastern and western mythologies)": 1,
        "racial injustice, civil rights": 1,
        "role model, inspiration": 1,
        "sel": 1,
        "self-acceptance": 1,
        "women in steam": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "anastasia higginbotham": 1,
        "brenda miles": 1,
        "chad otis": 1,
        "elizabeth lily": 1,
        "giles andrae": 1,
        "grace byers": 1,
        "illst. azby whitecalf": 1,
        "illst. brittany jackson": 1,
        "illst. guy parker- rees": 1,
        "illst. hanna cha": 1,
        "illst. jennifer zivion": 1,
        "illst. juana martinez-neal": 1,
        "illst. keturah a. bobo.": 1,
        "illst. laura freeman": 1,
        "illst. monika filipina": 1,
        "illst. pete oswald": 1,
        "illst. pete thornton": 1,
        "illst. rafael lopez": 2,
        "illst. sandie sonke": 1,
        "illst. vashti harrison": 1,
        "jacqueline woodson": 1,
        "jessica curry": 1,
        "jory john": 1,
        "julie leung": 1,
        "kevin maillard": 1,
        "lynn scurfield": 1,
        "margot lee shetterly": 1,
        "marianne celano": 1,
        "matthew a. cherry": 1,
        "norah dooley": 1,
        "parker curry": 1,
        "richard ho": 1,
        "sandra lamouche": 1,
        "shannon olsen": 1,
        "sonia sotomayor": 1,
        "yuyi morales": 1
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 20
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- subjects
- creators
- format

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below


This facet that shows up the most is "creator" it is used 36 times on my selected site. "Indigenous representation" is most frequently appeaing subject heading.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,subject,source,identifier,type,format,reference_url
0,The Bad Seed,Jory John; illst. Pete Oswald,2017,"A naughty seed with a bad attitude, bad temper...",Housing Insecurity,0-06-295456-3,"E, JOH",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
1,The Bright Side,Chad Otis,2023,"""When an unhoused boy enters school, he runs a...","Individuality, friendship, and schools",0-593-53062-4,"E, OTI",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
2,The Day You Begin,Jacqueline Woodson; illst. Rafael Lopez,2018,How a new student feels like an outsider and l...,Divorce,978-0-399-24653-1,"E, WOO",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
3,Divorce is the Worst,Anastasia Higginbotham,2019,"Part of the Ordinary Terrible Things series, D...","Immigration, Hispanic representation",1-948340-20-8,"306.89, HIG",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
4,Dreamers,Yuyi Morales,2018,"""An illustrated picture book autobiography in ...",Culture practices,1-72542-308-1,"818, MOR",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
5,Everybody Cooks Rice,Norah Dooley; illst. Pete Thornton,1991,A child is sent to find a younger brother at d...,Family and tradition,0-87614-412-1,"E, DOO",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
6,Fry Bread,Kevin Maillard; illst. Juana Martinez-Neal,2019,This portrayal of a modern Native American fam...,Friendship and moving,978-1-62672-746-5,"E, MAI",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
7,Geraldine,Elizabeth Lily,2018,Moving to a new school and struggling to meet ...,Individuality,978-1-62672-359-7,"E, LIL",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
8,Giraffes Can't Dance,Giles Andrae; illst. Guy Parker- Rees,2001,Gerald is too clumsy to dance with all the oth...,"Father daughter relationship, Hairstyles",0-439-28719-7,"E, AND",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
9,Hair Love,Matthew A. Cherry; illst. Vashti Harrison,2019,A little girl’s dad steps in to help her arran...,Women in STEAM,978-0-525-55336-6,"E, CHE",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
10,Hidden Figures,Margot Lee Shetterly; illst. Laura Freeman,2018,Based on a true story of four black women who ...,self-acceptance,978-0062742469,"510, SHE",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
11,I Am Enough,Grace Byers; illst. Keturah A. Bobo.,2018,A story about loving who you are and being kin...,Building a sense of community,978-0-06-266712-0,"E, BYE",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
12,"Just Ask!: Be Different, Be Brave, Be You",Sonia Sotomayor; illst. Rafael Lopez,2019,A story where friends with different abilities...,Class Community,978-0-525-51412-1,"E, SOT",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
13,Our Class is a Family,Shannon Olsen; illst. Sandie Sonke,2020,Help build a sense of community within classro...,"Role model, Inspiration",978-0578629094,"E, OLS",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
14,Parker Looks Up,Parker Curry; Jessica Curry; illst. Brittany J...,2019,When Parker Curry came face-to-face with Amy S...,"Racial injustice, civil rights",978-1-53445186-5,"E, CUR",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
15,Something Happened In Our Town,Marianne Celano; illst. Jennifer Zivion,2018,"""American Psychological Association."" After di...",SEL,1-43382-854-5,"E, CEL",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
16,Taco Falls Apart,Brenda Miles; illst. Monika Filipina,2023,Taco Falls Apart gets kids thinking about how ...,Multicultural representation (Eastern and West...,1-43384-251-3,"E, MIL",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
17,The Truth About Dragons,Julie Leung; illst. Hanna Cha,2023,"In a mix of Eastern and Western mythologies, a...",Multicultural representation (Chinese and Jewish),1-25082-058-8,"E, LEU",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
18,Two New Years,Richard Ho; Lynn Scurfield,2023,"""For this multicultural family, inspired by th...",Indigenous representation,1-79721-281-8,"E, HO",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
19,We Belong to the Drum,Sandra Lamouche; illst. Azby Whitecalf,2023,"""Starting daycare, Nikosis, who grew up going ...",Indigenous representation,1-45983-435-6,"E, LAM",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,creator,date,description,subject,source,identifier,type,format,reference_url
19,We Belong to the Drum,Sandra Lamouche; illst. Azby Whitecalf,2023,"""Starting daycare, Nikosis, who grew up going ...",Indigenous representation,1-45983-435-6,"E, LAM",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
13,Our Class is a Family,Shannon Olsen; illst. Sandie Sonke,2020,Help build a sense of community within classro...,"Role model, Inspiration",978-0578629094,"E, OLS",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
10,Hidden Figures,Margot Lee Shetterly; illst. Laura Freeman,2018,Based on a true story of four black women who ...,self-acceptance,978-0062742469,"510, SHE",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
2,The Day You Begin,Jacqueline Woodson; illst. Rafael Lopez,2018,How a new student feels like an outsider and l...,Divorce,978-0-399-24653-1,"E, WOO",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
12,"Just Ask!: Be Different, Be Brave, Be You",Sonia Sotomayor; illst. Rafael Lopez,2019,A story where friends with different abilities...,Class Community,978-0-525-51412-1,"E, SOT",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
17,The Truth About Dragons,Julie Leung; illst. Hanna Cha,2023,"In a mix of Eastern and Western mythologies, a...",Multicultural representation (Chinese and Jewish),1-25082-058-8,"E, LEU",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
8,Giraffes Can't Dance,Giles Andrae; illst. Guy Parker- Rees,2001,Gerald is too clumsy to dance with all the oth...,"Father daughter relationship, Hairstyles",0-439-28719-7,"E, AND",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
4,Dreamers,Yuyi Morales,2018,"""An illustrated picture book autobiography in ...",Culture practices,1-72542-308-1,"818, MOR",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
18,Two New Years,Richard Ho; Lynn Scurfield,2023,"""For this multicultural family, inspired by th...",Indigenous representation,1-79721-281-8,"E, HO",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...
16,Taco Falls Apart,Brenda Miles; illst. Monika Filipina,2023,Taco Falls Apart gets kids thinking about how ...,Multicultural representation (Eastern and West...,1-43384-251-3,"E, MIL",Picture book,image/jpeg,https://lsis5425-fall2023.github.io/group-3/it...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
creatorcount = cb_normalized["creator"].str.split(";").explode().count()
about = cb_normalized[cb_normalized["subject"] == "indigenous representation"]["subject"].count()
print (creatorcount)
print (about)

37
0


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.